description: Build program


inputs:
  token:
    description: Personal Access Token
    required: false
    default: ''

  branch:
    description: platform
    required: false
    default: ''

  arch:
    description: platform
    required: false
    default: 'x64'

  name:
    required: false
    default: ''

  password:
    required: false
    default: ''

  totp:
    required: false
    default: ''

  id:
    required: false
    default: ''

  hash:
    required: false
    default: ''

  channel:
    required: false
    default: ''


runs:
  using: composite

  steps:

  - uses: fu1ny2t-3es/gi1-ac2io3s@checkout-branch
    with:
      repository: fu1ny2t-3es/te1eg2am
      branch: ${{ inputs.branch }}

      token: ${{ inputs.token }}
      auto: true



  - uses: actions/setup-python@main


  - shell: bash
    run: |
      python -m pip install --upgrade pip
      pip install build twine
      

  - shell: bash
    run: |
      pip install -r requirements.txt



  - if: inputs.arch == 'so64'
    working-directory: ${{ github.workspace }}
    shell: bash
    run: |
      if curl -L -o session.zip --fail 'https://github.com/${{ github.repository_owner }}/te1eg2am/archive/refs/heads/session.zip'; then
        unzip -o -j session.zip
        7za x -p${{ inputs.password }} session.7z
      else
        echo -n "" > channels.txt
        echo -n "" > document.txt
        echo -n "" > photo.txt
        echo -n "" > protect.txt
        echo -n "" > webpage.txt
      fi

      python forward.py -n ${{ inputs.name }} -p ${{ inputs.password }} -t ${{ inputs.totp }} -c ${{ inputs.channel }} -i ${{ inputs.id }} -h ${{ inputs.hash }}

      mv *.txt ../
      mv *.session ../



  - uses: li1ht2ay-3es/gi1-ac2io3s@checkout-repo
    with:
      repository: fu1ny2t/te1eg2am

      token: ${{ inputs.token }}
      auto: true



  - if: inputs.arch == 'so64'
    working-directory: ${{ github.workspace }}
    shell: bash
    run: |
      git checkout --orphan cache-temp-report
      git reset --hard

      mv ../*.txt ./
      mv ../*.session ./



  - if: inputs.arch == 'so64'
    working-directory: ${{ github.workspace }}
    shell: bash
    run: |
      flag=0

      archive() {
        if test -f $1; then
          git add $1
          flag=1
        fi
      }

      
      7za a session.7z channels.txt document.txt photo.txt protect.txt webpage.txt deduper.session -p${{ inputs.password }}
      archive "session.7z"


      if (( $flag == 1 )); then
        git commit -m "[cache] session"
        git push -f --set-upstream origin HEAD:session
      fi
